### ISSUE TITLE
5 разных логических варианта для поинтов

### ISSUE THREAD

**Issue by Sparrowack** [behowtour/ITS#105]
- [x]  - обычный имеющийся сейчас в игре (травинка)
- [x] - ускоряющий в 1.5 раза сильнее (цветок)
- [x] - не дающее притягивание, только лопающееся (росинка) (анимация)
- [x] - неизбежный game over при сталкивании (паучок) (сразу в кокон и падение) замена спрайта ГГ на Кокон
- [x] - исчезающий после первого применения (сухая травинка)
- [x] - медленно поднимающий вверх как на шарике (одуванчик)

 - при сложности , убрать временно паучка
- вместо паучка думаю лучше Колючка, анимация проще и более понятно
- еще более просто вариант - двигающийся поинт, например мушка

**Comment by behowtour** [comment]
А цветок усиливает притягивание к нему или ускоряет как в Итси - при пролёте сквозь него?

**Comment by behowtour** [comment]
сделаны простые без анимаций описанные типы поинтов. Наведение красоты по каждому из них будет в виде отдельных ишью
