### ISSUE TITLE
переработка генератора поинтов

### ISSUE THREAD

**Issue by Sparrowack** [behowtour/ITS#107]
наверное 
- травинка процентов 80 %
- цветок 10 %
- остальные 4 внутри на выбор не более 10 % от общего

**Comment by Sparrowack** [comment]
вообще разброс должен касаться уровня / сложности / высоты, поэтому тут скорее о возможности выстраивать разброс через доли из 100, а не о выставлении процентов , antik это скорее о начале , но не самом, почувствовать игру, самое начало думаю вообще будет без каких либо вариаций поинтов , только lvl1 , до 100-150 метров например, появление нового необычного поинта , сначала очень редко , это всегда кайф

**Comment by Sparrowack** [comment]
блуждала мысль, проблема не в генераторе, а в том что не проработана система поинтов, создам issue , генератор - просто чтоб работал под новую систему

**Comment by behowtour** [comment]
Генератор переделан так, что новые типы поинтов просто в массив добавляем, а этому массиву префабов поинтов соответствует массив целых чисел - соответствующих шансов появления. Эти массивы уже будут из кода для соответствующих этапов прохождения и настраиваться (изначально в инспекторе задается, в коде пока никаких влияний на эти массивы нет).
Также сделано так, что поинты с тэгом RedLeaf (осталось легаси название пока что 😀 ) не могут повториться дважды, друг за другом то есть
