### ISSUE TITLE
Настроить фейковый поинт

### ISSUE THREAD

**Issue by behowtour** [behowtour/ITS#130]
Поинт, который при нажатии на него не притягивает, а просто пропадает

- [x] добавить анимацию постонную
- [x] доработать, чтобы веревка в него выстреливала и только после этого он "начинал пропадать", и при этом веревка пропадала
- [x] добавить анимацию как пропадает поинт (росинка утекает например, или жучок листик оказывает жуком и убегает и т.п.)
- [x] веревка пропадает через пол секунды (не дожидаясь окончания анимации) или меньше, настроить чтобы красиво и играбельно было

**Comment by Sparrowack** [comment]
Нет анимации в мейне на момент 1.12.22

**Comment by behowtour** [comment]
А, ну так я её и не делал оказывается. Во даю
