### ISSUE TITLE
Настроить килл-поинт

### ISSUE THREAD

**Issue by behowtour** [behowtour/ITS#131]
Поинт, который нельзя нажимать и касаться 
@Sparrowack  мне кажется надо оставить только вариант касания - нажатие на него не должно убивать по идее, как думаешь? По нажатию можно сделать так, что или будет работать как с фейковым поинтом - то есть веревка не зацепляется, или например можно сделать если это будет насекомое какое-то, то чтобы оно просто начало медленно в сторону ГГ некоторое время двигаться.

- [x] добавить анимацию постоянную
- [ ] #154
- [x] добавить килл-поинт в виде насекомого (с анимацией и всеми делами)
- [x] сделать чтобы килл поинт насекомого двигался от края экрана к другому краю и обратно

**Comment by Sparrowack** [comment]
шип предполагался аналогом кактуса в итси - он гейм оверит при касании об него но только во время притягивания, в остальных случаях мимо него можно пролетать, поинта аналогом мошки в итси - мгновенное убийство, я предполагал комара, думаю все 3 варианта поинтов к месту, и инстант килл и при притягивании и при любом касании, только на этот уровень я бы оставил только шип и комара
