### ISSUE TITLE
сделать эффект нажатия на поинты

### ISSUE THREAD

**Issue by behowtour** [behowtour/ITS#16]

**Comment by behowtour** [comment]
@Sparrowack нашел баг: с оранжевыми листами после их уничтожения остается "облачко" нажатия.
![image](https://user-images.githubusercontent.com/37346495/171233052-7f469916-0a14-42a7-a61d-55fd78f2c8ae.png)

**Comment by Sparrowack** [comment]
Fixed

**Comment by behowtour** [comment]
всё ещё остается дымок
